#### RT Factor Filtering Function
# Functional Draft
# Feb. 20, 2019
# input a raw lobset


library(tidyverse)


# where are source files?
setwd("C:/Users/TSQ/Desktop/Daniel Lowenstein/KimT_cleaning/")

# Load data and RT Factor database
# May need to change -X0 or -X1 in source csv
original_data <- read.csv("Edited_KimT_Pos_bw20_LOBSTAHS_screened_peakdata_2019-02-26T10-58-14_AM-0500.csv")
RT_Factor_Dbase <-read.csv("C:/Users/TSQ/Desktop/Daniel Lowenstein/RT_Factors/Hummel RtF Master Database - rtf_data.csv")


RT_Factor_Sort <- function(original_data, RT_Factor_Dbase){

  library(tidyverse)

  ### Check Inputs ###

  if (is.null(RT_Factor_Dbase$Mean_DNPPE_Factor)) {

    stop("Looks like input 'RT_Factor_Dbase' is not the right one.\n",
         "Make sure you're using an up to date database with",
         "a Mean DNPPE Factor for each compound.")

  }

  if (is.null(original_data$match_ID)) {

    stop("Input data.frame does not contain a 'match_ID' column.",
         "Please use a data.frame generated by 'getLOBpeaklist'.")

  }

  if (is.null(original_data$compound_name)) {

    stop("Input data.frame does not contain a 'compound_name' column.",
         "Please use a data.frame generated by 'getLOBpeaklist'.")

  }

  if (is.null(original_data$LOBdbase_mz)) {

    stop("Input data.frame does not contain a 'LOBdbase_mz' column.",
         "Please use a data.frame generated by 'getLOBpeaklist'.")

  }

  if (is.null(original_data$peakgroup_rt)) {

    stop("Input data.frame does not contain a 'peakgroup_rt' column.",
         "Please use a data.frame generated by 'getLOBpeaklist'.")

  }

  if (is.null(original_data$FA_total_no_C)) {

    stop("Input data.frame does not contain a 'FA_total_no_C' column.",
         "Please use a data.frame generated by 'getLOBpeaklist'.")

  }

  if (is.null(original_data$FA_total_no_DB)) {

    stop("Input data.frame does not contain a 'FA_total_no_DB' column.",
         "Please use a data.frame generated by 'getLOBpeaklist'.")

  }


  # make sure peakgroup rt is numeric
  original_data$peakgroup_rt <- as.numeric(original_data$peakgroup_rt)

  # Extract correct DNPPE retention time
  DNPPE_RT <- original_data$peakgroup_rt[which(grepl("DNPPE", original_data$compound_name))]
  #DNPPE_RT <- DNPPE_RT[***]  #if there are two DNPPE peaks, index to the correct one

  # Add column for DNPPE factor and an empty one for flagging
  original_data <- original_data %>%
    mutate(DNPPE_Factor = peakgroup_rt/DNPPE_RT, Flag = "None") %>%
    filter(species != "NA")

  # isolate major intact polar lipid classes, unoxidized (need to add pigments, etc.)
  Main_Lipids <- original_data %>%
    filter(degree_oxidation == "0",
           species == "BLL"|
             species == "DGCC" |
             species == "DGTS_DGTA" |
             species == "PE" |
             species == "PG" |
             species == "PC" |
             species == "MGDG" |
             species == "DGDG" |
             species == "SQDG"|
             species == "TAG"|
             species == "DAG"|
             species == "FFA")

  # isolate oxidized lipids into df
  Ox_Lipids <- original_data %>%
    filter(degree_oxidation > 0)

  # flag known vs unknown by checking whether grepl returns anything in the database
  for (i in 1:length(Main_Lipids$compound_name)){
    which_row <- which(grepl(paste0("^", Main_Lipids$compound_name[i], "$"), RT_Factor_Dbase$compound_name))

    if(is.na(RT_Factor_Dbase$Mean_DNPPE_Factor[which_row]) != TRUE ){
      Main_Lipids$Flag[i] = "Known"
    }else{
      Main_Lipids$Flag[i] = "Unknown"
    }

  }

  # separate into two dfs
  Known_RtFs <- Main_Lipids %>% filter(Flag == "Known")
  Unknown_RtFs <- Main_Lipids %>% filter(Flag == "Unknown")

  # for each compound in the "Known" df, grab its corresponding row number in RT_Factor_Dbase,
  # then flag it as follows
  # first check if it's in a 10%

  for (i in 1:length(Known_RtFs$compound_name)){
    which_row <- as.numeric(which(grepl(paste0("^", Known_RtFs$compound_name[i], "$"), RT_Factor_Dbase$compound_name)))

    if(Known_RtFs$DNPPE_Factor[i] < (RT_Factor_Dbase$Mean_DNPPE_Factor[which_row]*1.1) & Known_RtFs$DNPPE_Factor[i] > (RT_Factor_Dbase$Mean_DNPPE_Factor[which_row]*0.9)){
      if(Known_RtFs$DNPPE_Factor[i] < (RT_Factor_Dbase$Mean_DNPPE_Factor[which_row]*1.05) & Known_RtFs$DNPPE_Factor[i] > (RT_Factor_Dbase$Mean_DNPPE_Factor[which_row]*0.95)){
        if(RT_Factor_Dbase$ms2_verified[which_row] == "Yes"){
          Known_RtFs$Flag[i] = "ms2v"
        }else{
          Known_RtFs$Flag[i] = "5%_rtv"
        }
      }else{
        (Known_RtFs$Flag[i] = "10%_rtv")
      }
    }else{
      Known_RtFs$Flag[i] = "Red"
    }
  }



  # combine known and unknown dfs
  Combined <- rbind(Known_RtFs, Unknown_RtFs)

  # change levels of colors so they plot in the right order
  Combined$Flag = factor(Combined$Flag, levels = c("Red", "ms2v", "5%_rtv", "10%_rtv", "Unknown"))

  Flagged_Data <- original_data
  Flagged_Data[Flagged_Data$match_ID %in% Combined$match_ID, "Flag"] <- as.character(Combined$Flag)
  Flagged_Data <<- Flagged_Data
}


RT_Factor_Sort(original_data, RT_Factor_Dbase)

#####################
# From here, giving the option to generate mz vs. rt graphs
# for each of the major classes.

# add a column for plot labelling by C and DB #
lipidclass <- Flagged_Data %>%
  mutate(C_DB = paste0(str_extract(FA_total_no_C, "\\d+"), ":", str_extract(FA_total_no_DB, "\\d+")))

# going through the big nine lipids plus TAGs, DAGs, and FFAs
lipid_classes <- c("DGCC", "DGTS_DGTA", "PC", "PE", "PG", "MGDG", "DGDG", "SQDG", "TAG", "DAG", "FFA")

# and plot each, saving a copy to the working directory
for (i in 1:length(lipid_classes)){
  Lipid <- lipidclass %>%
    filter(species == paste(lipid_classes[i]))

  print(ggplot(Lipid, aes(x = DNPPE_Factor, y = LOBdbase_mz, color =  Flag))+
    geom_point()+
    geom_errorbarh(aes(xmax = RTF_Window*1.1, xmin = RTF_Window*0.9, height = 0.2))+
    geom_text(aes(label = C_DB, hjust = 1, vjust = 2))+
    ggtitle(paste0("M/Z vs. RT in ", lipid_classes[i])))
  # ggsave(filename = paste0(lipid_classes[i], "_MZRT_Nicole.tiff"),
  #        plot = last_plot(),
  #        device = "tiff",
  #        width = 22, height = 17)

  }
